AWSTemplateFormatVersion: '2010-09-09'
Description: Test Lambda Layer template
Parameters:
  Name:
    Type: String
  CodeBucket:
    Type: String
  CodeFile:
    Type: String
  License:
    Type: String
    Default: ""
Conditions:
  HasLicense:
    !Not [!Equals [!Ref License, ""]]
Resources:
  Layer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.6
      Content: 
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeFile
      Description: This layer has a helper function for abstracting sqs functions
      LayerName: !Ref Name
      LicenseInfo: 
        !If
          - HasLicense
          - !Ref License
          - !Ref "AWS::NoValue"